updated copy
radicle-dev/radicle.xyz pull request #130
Opened 2020-11-12 17:37 UTC by abbey-titcomb

Updated roadmap section, last feature in feature section, added community channel links, and fixed up some typos,

2020-11-12 18:05 UTC, abbey-titcomb commented
@lftherios @juliendonck @cloudhead - took a shot at the roadmap copy, take a look and let me know what you think.

2020-11-13 14:25 UTC, juliendonck commented
Hey @abbey-titcomb you've edited the index files in the `docs` folder. It will be overwritten when the website is built. You need to change the `index.html.mustache` file. You also need to make sure to run `make` when you're done editing. I can pair with you to make this work. But these changes will basically be overwritten as soon as someone else works on this.

2020-11-13 14:29 UTC, brandonhaslegs requested changes
**IMPORTANT**: You've edited the **index.html** file here. You need to go into the index.html.mustache file and make all these edits again. Julien and I have accidentally also done this a bunch of times too. ☹️

2020-11-13 14:29 UTC, brandonhaslegs commented on docs/index.html
> +              <p>No need to trust anyone to keep your work safe or online</p>
Missing a period here

2020-11-13 14:29 UTC, brandonhaslegs commented on docs/index.html
> +              <p>Code collaboration as you know it. Work better together with bug reporting, code review, and discussions - all offline and local-first. </p>
Should this be code **reviews**?

2020-11-13 16:09 UTC, abbey-titcomb commented
Yikes, alright thanks guys. Will edit the right file. Should I just leave these changes here or does it not matter since it'll be overwritten?

2020-11-16 13:44 UTC, lftherios commented on docs/index.html
> +              <h4>Create with your <br/> community</h4>
I prefer "create value with your community" but this also does it.

2020-11-16 13:45 UTC, lftherios commented on docs/index.html
> +              <p>We're building everything open-source and public by default.</p>
prefer as "free software" vs open-source

2020-11-16 13:46 UTC, lftherios commented on docs/index.html
> +              <p>The first release of our peer-to-peer network and desktop client. Join the network and start hosting your code peer-to-peer.</p>
"in a tamper-proof, peer-to-peer way"

2020-11-16 13:48 UTC, lftherios commented on docs/index.html
> +              <h3>Scaling up with Ethereum</h3>
scaling and ethereum might draw some memes. maybe "go further with ethereum" or something like that?

2020-11-16 13:49 UTC, lftherios reviewed
I left a few minor points here and there.

2020-11-17 10:14 UTC, abbey-titcomb commented on docs/index.html
> +              <p>We're building everything open-source and public by default.</p>
I don't think we can replace open-source with free software and have the sentence make sense. I think open-source is more of an adjective than a noun, like free software is. Let's keep it as it is.

2020-11-17 10:15 UTC, abbey-titcomb commented on docs/index.html
> +              <p>The first release of our peer-to-peer network and desktop client. Join the network and start hosting your code peer-to-peer.</p>
I don't see what tamper-proof adds to this sentence. How about we say "Join the network and start securely hosting your code peer-to-peer" instead?

2020-11-17 10:22 UTC, abbey-titcomb commented on docs/index.html
> +              <h3>Scaling up with Ethereum</h3>
Yeah that could work, or "expand with ethereum"?

2020-11-17 10:23 UTC, abbey-titcomb commented on docs/index.html
> +              <h4>Create with your <br/> community</h4>
I think we agreed on Create with your community bc we use "value" in one of the sub bullets, so let's keep it as it is.

2020-11-17 10:33 UTC, abbey-titcomb commented on pages/index.html.mustache
> +              <p>Join the network and give peer-to-peer code hosting a go with the first version of our desktop client.</p>
```suggestion
              <p>Join the network and give secure peer-to-peer code hosting a go with the first version of our desktop client.</p>
```

2020-11-17 10:33 UTC, abbey-titcomb commented on pages/index.html.mustache
> +              <p>The first release of our peer-to-peer network and desktop client. Join the network and start hosting your code peer-to-peer.</p>
```suggestion
              <p>The first release of our peer-to-peer network and desktop client. Join the network and start securely hosting your code peer-to-peer.</p>
```

2020-11-17 10:33 UTC, abbey-titcomb commented on pages/index.html.mustache
> +              <h3>Scaling up with Ethereum</h3>
```suggestion
              <h3>Expanding with Ethereum</h3>
```

2020-11-17 11:46 UTC, cloudhead commented on docs/index.html
> +              <p>The first release of our peer-to-peer network and desktop client. Join the network and start hosting your code peer-to-peer.</p>
"tamper-evident" would be the correct term (if we want to add anything)

2020-11-17 11:47 UTC, cloudhead commented on docs/index.html
> +              <h3>Scaling up with Ethereum</h3>
I like "going further with ethereum" or something like that

2020-11-17 11:47 UTC, cloudhead commented on docs/index.html
> +              <p>Join the network and give peer-to-peer code hosting a go with the first version of our desktop client.</p>
```suggestion
              <p>Join the network and give peer-to-peer code hosting a go with the first release of our desktop client.</p>
```

2020-11-17 11:49 UTC, cloudhead commented on pages/index.html.mustache
> +              <p>Code collaboration as you know it. Work better together with bug reporting, code reviews, and discussions - all offline and local-first.</p>
I'd say "offline-first" or "local-first", not "offline and local-first", because that sounds like it's an offline-only experience.

2020-11-17 11:49 UTC, cloudhead commented on pages/index.html.mustache
> +              <h3>Expanding with Ethereum</h3>
expanding sounds weird, like imperialist or something

2020-11-17 11:50 UTC, cloudhead commented on pages/index.html.mustache
> +              <p>We're building everything open-source and public by default.</p>
```suggestion
              <p>We're building everything open-source and publicly.</p>
```
Though I'd just prefer "We're building everything open-source and with the community"

2020-11-17 14:57 UTC, abbey-titcomb commented on docs/index.html
> +              <p>The first release of our peer-to-peer network and desktop client. Join the network and start hosting your code peer-to-peer.</p>
Cool, I'll be resolving this and sticking with "securely hosted" for now.

2020-11-17 14:58 UTC, abbey-titcomb commented on docs/index.html
> +              <h3>Scaling up with Ethereum</h3>
Cool, I can dig this. Will change to Going Further. Resolving

2020-11-17 14:59 UTC, brandonhaslegs approved these changes

2020-11-17 16:21 UTC, abbey-titcomb commented on pages/index.html.mustache
> +              <p>We're building everything open-source and public by default.</p>
I like that 

```suggestion
              <p>We're building everything open-source and with our community.</p>
```

2020-11-17 17:17 UTC, cloudhead commented on pages/index.html.mustache
> +              <p>Code collaboration as you know it. Work better together with bug reporting, code reviews, and discussions - all offline and local-first.</p>
yeah that works. meta: can we use the correct `&mdash;` for the `-`?

2020-11-17 17:18 UTC, cloudhead approved these changes

2020-11-17 22:12 UTC, lftherios approved these changes

2020-11-18 09:28 UTC, juliendonck approved these changes

2020-11-18 09:30 UTC, merged

2020-11-18 09:30 UTC, abbey-titcomb commented
🎆🎆🎆🎆