Added mailchimp link + removed formspree
radicle-dev/radicle.xyz pull request #131
Opened 2020-11-13 12:25 UTC by abbey-titcomb

Embedded the mailchimp sign up form so we can keep the current flow (subscribe -> /subscribe.html). Right now the form redirects to radicle.xyz/subscribed.html - hopefully this is the right link, if not lmk and I'll change it in mailchimp flow.

Removed some formspree code that I don't think is necessary for mailchimp, but check it out and let me know.

2020-11-13 13:44 UTC, brandonhaslegs requested changes

2020-11-13 13:44 UTC, brandonhaslegs commented on docs/index.html
> -          <form class="main-cta" action="https://formspree.io/xrgbwygl" method="POST" autocomplete="off">
Can you keep in the `autocomplete="off"` bit in the form tag plz

2020-11-13 13:44 UTC, brandonhaslegs commented on docs/index.html
> -          <form action="https://formspree.io/xrgbwygl" autocomplete="off" method="POST">
Same here

2020-11-13 14:05 UTC, juliendonck approved these changes
Looks good. One thing though, the logo you used on the mailchimp email is really bad quality. It's worth uploading a better version:

<img width="319" alt="Screenshot 2020-11-13 at 15 03 08" src="https://user-images.githubusercontent.com/2326909/99080524-b5909780-25c1-11eb-84e0-0ef388d25c4a.png">

2020-11-13 14:05 UTC, juliendonck commented on docs/index.html
> +          <form class="main-cta" action="https://xyz.us2.list-manage.com/subscribe/post?u=6c7bba7ab992717860dcec6eb&amp;id=f960345a90" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-
```suggestion
          <form class="main-cta" action="https://xyz.us2.list-manage.com/subscribe/post?u=6c7bba7ab992717860dcec6eb&amp;id=f960345a90" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate autocomplete="off">
```

2020-11-13 14:05 UTC, juliendonck commented on docs/index.html
> +          <form action="https://xyz.us2.list-manage.com/subscribe/post?u=6c7bba7ab992717860dcec6eb&amp;id=f960345a90" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" c
```suggestion
          <form action="https://xyz.us2.list-manage.com/subscribe/post?u=6c7bba7ab992717860dcec6eb&amp;id=f960345a90" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate autocomplete="off">
```

2020-11-13 17:58 UTC, abbey-titcomb commented on docs/index.html
> +          <form class="main-cta" action="https://xyz.us2.list-manage.com/subscribe/post?u=6c7bba7ab992717860dcec6eb&amp;id=f960345a90" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-
resolved this in my latest commit

2020-11-13 17:58 UTC, abbey-titcomb commented on docs/index.html
> -          <form action="https://formspree.io/xrgbwygl" autocomplete="off" method="POST">
added

2020-11-13 17:58 UTC, abbey-titcomb commented on docs/index.html
> -          <form class="main-cta" action="https://formspree.io/xrgbwygl" method="POST" autocomplete="off">
added

2020-11-16 13:46 UTC, juliendonck approved these changes

2020-11-17 10:32 UTC, brandonhaslegs requested changes
Why are there two different fonts in the MailChimp email? All Helvetica should work fine.

![image](https://user-images.githubusercontent.com/4406983/99379109-88e1c600-28c8-11eb-99fc-6402b2d99a5b.png)

2020-11-17 11:26 UTC, brandonhaslegs commented
And maybe should have a more generic email than your email in there?

2020-11-17 11:34 UTC, abbey-titcomb commented
> Why are there two different fonts in the MailChimp email? All Helvetica should work fine.
> 
> ![image](https://user-images.githubusercontent.com/4406983/99379109-88e1c600-28c8-11eb-99fc-6402b2d99a5b.png)

Didn't notice. Can change in Mailchimp. 

Also will add a Radicle Foundation email when we decide which one to use. Ange is going to let me know.

2020-11-18 12:30 UTC, brandonhaslegs approved these changes

2020-11-18 13:05 UTC, abbey-titcomb commented
Merging 👽

2020-11-18 13:06 UTC, merged