Limit #features h1.druk font-size
radicle-dev/radicle.xyz pull request #143
Opened 2020-11-30 10:46 UTC by NunoAlexandre

It becomes too big on ultra-wide screens.

Currently: 
![Screenshot from 2020-11-30 11-25-14](https://user-images.githubusercontent.com/7075260/100600170-35786a80-3301-11eb-9ca4-237f7a86b16f.png)

With fix:

![fix](https://user-images.githubusercontent.com/7075260/100600532-b20b4900-3301-11eb-8e56-18c8b700efe0.png)

2020-11-30 10:50 UTC, NunoAlexandre commented
Also fixed the short line-height for this element on bigger screens :point_up:

2020-11-30 11:26 UTC, juliendonck commented
<img width="85" alt="Screen Shot 2020-11-30 at 12 25 55" src="https://user-images.githubusercontent.com/2326909/100604707-33190f00-3307-11eb-9402-a676754253c1.png">
still cut off

2020-11-30 12:20 UTC, NunoAlexandre commented
@juliendonck can you have another look?

2020-12-01 13:18 UTC, brandonhaslegs submitted a review, later dismissed

2020-12-03 11:35 UTC, juliendonck requested changes
<img width="292" alt="Screen Shot 2020-12-03 at 12 34 57" src="https://user-images.githubusercontent.com/2326909/101013014-f5fd8880-3563-11eb-9530-bad85e53811e.png">
Still cut for me ?

2020-12-03 11:35 UTC, juliendonck commented
> <img alt="Screen Shot 2020-12-03 at 12 34 57" width="292" src="https://user-images.githubusercontent.com/2326909/101013014-f5fd8880-3563-11eb-9530-bad85e53811e.png">
> 
> Still cut for me ?

On my 27 inch screen

2020-12-03 11:43 UTC, NunoAlexandre commented
@juliendonck you are right. Apologies for the noise and time taken. Pushed a fix, checked it for several screen sizes.

@brandonhaslegs was there a design intent with setting the line-height to < 100% or was it just leftovers?

2020-12-03 11:48 UTC, brandonhaslegs commented
> @brandonhaslegs was there a design intent with setting the line-height to < 100% or was it just leftovers?

Can you comment this on the style you're referring to? Don't know which one you mean.

2020-12-03 12:50 UTC, NunoAlexandre commented
> > @brandonhaslegs was there a design intent with setting the line-height to < 100% or was it just leftovers?
> 
> @NunoAlexandre Can you comment this on the style you're referring to? Don't know which one you mean.

On the one affected here, the `.druk` class.

2020-12-03 14:30 UTC, brandonhaslegs commented
You could remove it but then you need to add a line-height style to the footer `h1`. All other druk headlines already have `line-height` applied separately.

2020-12-18 08:39 UTC, brandonhaslegs commented on docs/styles/style.css
> -    line-height: 80%;
This changes the line height on mobile, which seems unrelated to the issue.

2020-12-18 11:09 UTC, brandonhaslegs approved these changes

2020-12-18 11:09 UTC, merged