Fix Timeline Length #178
radicle-dev/radicle.xyz pull request #179
Opened 2021-02-15 05:49 UTC by SNikhill

With this merge, the length of the timeline shall be fixed when viewed on a size different than the Computer Screen.

Basically, like in Computer Screen, the timeline is expanding itself across the whole width similarly, the timeline will expand itself across the whole height when viewed on a Phone/iPad/Tablet.

2021-02-15 05:51 UTC, SNikhill commented
Also, just wanted to point out that the path to the `styles.css` is not dynamic. It fails to load when `index.html` is viewed. I believe that it is due to the fact that the path has been hard coded in the `head` partial.

2021-02-25 15:54 UTC, brandonhaslegs commented
So in some viewports it's still overshooting the last dot a bit. The only way to fix it as far as I know (with CSS) is to have a lot of media queries that adjust the height of the line based on every small change in the paragraph lengths.

![image](https://user-images.githubusercontent.com/4406983/109170914-858c8f00-7781-11eb-8e05-bc4f6768a947.png)
![image](https://user-images.githubusercontent.com/4406983/109170969-91785100-7781-11eb-92ae-2cbda49d41db.png)
![image](https://user-images.githubusercontent.com/4406983/109179377-1d8e7680-778a-11eb-9547-fa8e8f70e2fe.png)

2021-02-25 17:52 UTC, SNikhill commented
I shall look into it.

2021-02-26 11:33 UTC, SNikhill commented
As requested, the line will _forever vanish into the unknown_ after 90% of it's length.

## Proof
![image](https://user-images.githubusercontent.com/51415616/109295183-4b3ff200-7854-11eb-9255-61fa56ec8d58.png)

If you guys want then, the extra media queries can be removed.

By the way, May I know the correct way to run the project on my local PC. My Browser can't seem to resolve the path for `stylesheet` and I have to manually change it every time which annoys me.

2021-02-26 11:43 UTC, cloudhead commented
You have to run your webserver from the `docs/` folder. Eg:
```
cd docs
python2 -m SimpleHTTPServer
```

2021-02-26 11:55 UTC, brandonhaslegs requested changes

2021-02-26 11:55 UTC, brandonhaslegs commented on docs/styles/style.css
> +    height: 100%;
Yep can remove all these now.

2021-02-26 12:00 UTC, SNikhill commented on docs/styles/style.css
> +    height: 100%;
Understood.

2021-02-26 12:07 UTC, SNikhill commented on docs/styles/style.css
> +    height: 100%;
Changes have been made.

2021-02-26 12:09 UTC, SNikhill commented on docs/styles/style.css
> +    height: 100%;
**NOTE:** The Force was pushed. Kindly fetch and then, reset your local branch to the Fetch Head to review the latest changes.

2021-03-01 12:12 UTC, brandonhaslegs approved these changes

2021-03-01 12:12 UTC, merged

2021-03-02 09:38 UTC, brandonhaslegs approved these changes