radicle org post
radicle-dev/radicle.xyz pull request #251
Opened 2021-07-14 15:04 UTC by juliendonck

Signed-off-by: Julien Donck <hello@juliendonck.com>

2021-07-14 16:19 UTC, lftherios approved these changes
:fireworks:

2021-07-15 09:07 UTC, juliendonck commented on blog/index.html.mustache
> +          <p class="meta">by <a href="https://twitter.com/lftherios" target="_blank">@abbey_titcomb</a> • <span>July 15th, 2021</span></p>
The link is to `href="https://twitter.com/lftherios"` but the text says a`@abbey_titcomb`

2021-07-15 09:07 UTC, juliendonck commented on blog/radicle-orgs.html.mustache
> +        <h2>On-chain, in-browser
```suggestion
        <h2>On-chain, in-browser</h2>
```

2021-07-15 09:07 UTC, juliendonck commented on blog/radicle-orgs.html.mustache
> +          Alongside the launch of Radicle Orgs comes the release of the Radicle web client, [app.radicle.network][https://app.radicle.network/]. Here, you can register ENS names for your orgs and cus
```suggestion
          Alongside the launch of Radicle Orgs comes the release of the Radicle web client, [app.radicle.network][https://app.radicle.network/]. Here, you can register ENS names for your orgs and customize their profiles. Our web client brings Radicle to the browser, making it easier to share your Radicle code with others.
```

2021-07-15 09:07 UTC, juliendonck commented on blog/radicle-orgs.html.mustache
> +          Alongside the launch of Radicle Orgs comes the release of the Radicle web client, app.radicle.network. Here, you can register ENS names for your orgs and customize their profiles profile. O
Duplicate paragraph

2021-07-15 09:28 UTC, brandonhaslegs requested changes

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          There are single-signer orgs (owned by one Ethereum address) or multi-signature orgs (owned by multiple Ethereum addresses). Multi-signature orgs are deployed with a [Gnosis Safe][https://g
```suggestion
          There are single-signer orgs (owned by one Ethereum address) or multi-signature orgs (owned by multiple Ethereum addresses). Multi-signature orgs are deployed with a [Gnosis Safe][https://gnosis-safe.io/]. This means Radicle users can deploy Safes to govern their org via Radicle Upstream or the Radicle web client.
```

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          There are single-signer orgs (owned by one Ethereum address) or multi-signature orgs (owned by multiple Ethereum addresses). Multi-signature orgs are deployed with a [Gnosis Safe][https://g
So we're calling it the Radicle web client now?

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          “Our Gnosis Safe integration with Radicle Orgs gives DAOs access to a new superpower where membership, admin control, governance and canonical project state is truly decentralized,” explain
```suggestion
          “Our Gnosis Safe integration with Radicle Orgs gives DAOs access to a new superpower where membership, admin control, governance and canonical project state are truly decentralized,” explains Julien Donck who leads the team developing [Radicle Upstream](https://docs.radicle.xyz/docs/getting-started), the Radicle desktop client. “As a go-to primitive for DAOs, integrating with Gnosis Safe first was a no-brainer for us.”
```

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +        <h2>On-chain, in-browser
```suggestion
        <h2>On-chain, in-browser</h2>
```

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          Widely used by Ethereum projects for treasury management, Gnosis Safe currently stewards [>$40billion USD][https://duneanalytics.com/tschubotz/gnosis-safe_2]. Although Gnosis Safe’s primary
```suggestion
          Widely used by Ethereum projects for treasury management, Gnosis Safe currently stewards [more than 40 billion USD][https://duneanalytics.com/tschubotz/gnosis-safe_2]. Although Gnosis Safe’s primary use is as an out-of-the-box asset management and coordination platform, its open-source architecture can also be modified by projects seeking to adapt its tooling for their own needs. 
```

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          “We view Radicle Org’s deployment on Gnosis Safe as an exciting open-source use of our tooling for aligned purposes",” says Gnosis CTO Stefan George. “Gnosis Safe is already the platform of
```suggestion
          “We view Radicle Org’s deployment on Gnosis Safe as an exciting open-source use of our tooling for aligned purposes,” says Gnosis CTO Stefan George. “Gnosis Safe is already the platform of choice for DAOs conducting decentralized treasury and membership management, and our integration with Radicle expands that application on a deeper level that we believe will provide greater service to the community.”
```

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          Alongside the launch of Radicle Orgs comes the release of the Radicle web client, [app.radicle.network][https://app.radicle.network/]. Here, you can register ENS names for your orgs and cus
> and customize their profiles profile.

not sure what this means

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          Alongside the launch of Radicle Orgs comes the release of the Radicle web client, app.radicle.network. Here, you can register ENS names for your orgs and customize their profiles profile. O
```suggestion
```

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          To get started with Radicle Orgs, download [Radicle Upstream](https://radicle.xyz/downloads.html) and follow our docs!
```suggestion
          To get started with Radicle Orgs, download [Radicle Upstream](https://radicle.xyz/downloads.html) and follow our [docs](docs.radicle.xyz)!
```

2021-07-15 09:28 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          To get started with Radicle Orgs, download [Radicle Upstream](https://radicle.xyz/downloads.html) and follow our docs!
update to the right URL to link directly to the Org docs

2021-07-15 11:03 UTC, brandonhaslegs requested changes

2021-07-15 11:03 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
> +          To get started with Radicle Orgs, download [Radicle Upstream](https://radicle.xyz/downloads.html) and follow our [docs](docs.radicle.xyz)!
Can you make this link a more specific link to the Orgs docs?

2021-07-15 11:04 UTC, brandonhaslegs requested changes

2021-07-15 11:04 UTC, brandonhaslegs commented on blog/radicle-orgs.html.mustache
>          <p>
This paragraph tag needs to be removed.

2021-07-15 13:43 UTC, abbey-titcomb approved these changes

2021-07-15 13:56 UTC, brandonhaslegs approved these changes

2021-07-15 13:57 UTC, merged