copy edits
radicle-dev/radicle.xyz pull request #259
Opened 2021-08-18 12:49 UTC by abbey-titcomb

Draft PR for #258 

Signed-off-by: abbey titcomb <abbeytitcomb@gmail.com>

2021-08-18 15:13 UTC, brandonhaslegs requested changes
Here are some suggestions and comments. Also I think we need to reevaluate the icons in each section. Some are repeated and some just don't match with the content they're next to.

2021-08-18 15:13 UTC, brandonhaslegs commented on docs/index.html
> +  Build your own value flows with "DevFi" lego blocks like donations, tips, and automated payouts</p>
what the hell does this mean 😂

2021-08-18 15:14 UTC, brandonhaslegs commented on docs/index.html
> +        <h1 class="druk">Code collaboration + Web3 = 🌱</h1>
We might as well say "GitHub for crypto" … this has the same energy to me.

2021-08-19 09:28 UTC, lftherios commented on docs/index.html
> +        <h1 class="druk">Code collaboration + Web3 = 🌱</h1>
We wanted something that talks more to our decentralized audience. That's why we went for that. I think it does the job of explaining the angle of Radicle.

2021-08-19 09:29 UTC, lftherios commented on docs/index.html
> +          <h2>For unstoppable, permissionless, and decentralized open-source development</h2>
hm I don't have a good substitute.

2021-08-19 09:29 UTC, lftherios commented on docs/index.html
> +              <p>Decentralize your open source project with Ethereum-powered Radicle Orgs.</p>
yeap

2021-08-19 09:29 UTC, lftherios commented on docs/index.html
> + Share ownership of repositories with multi-sigs</p>
I think it's important to explain ownership of what.

2021-08-19 09:29 UTC, lftherios commented on docs/index.html
> + Secure and anchor project state on-chain</p>
Works.

2021-08-19 09:30 UTC, lftherios commented on docs/index.html
>                <h4>Create with your <br/> community</h4>
I still prefer the "create with your community"

2021-08-19 09:30 UTC, brandonhaslegs commented on docs/index.html
> +        <h1 class="druk">Code collaboration + Web3 = 🌱</h1>
How about:

Your decentralized web3 workspace

![image](https://user-images.githubusercontent.com/4406983/130045194-a0d169e6-00e8-41ed-855d-49e1d2bb188e.png)

2021-08-19 09:31 UTC, lftherios commented on docs/index.html
> + Create and fund developer communities with NFT-based membership models</p>
Works

2021-08-19 09:31 UTC, lftherios commented on docs/index.html
> +  Build your own value flows with "DevFi" lego blocks like donations, tips, and automated payouts</p>
hehe fair. we can stick with the old version

2021-08-19 09:38 UTC, brandonhaslegs approved these changes

2021-08-19 09:39 UTC, merged